# Generated by Django 5.1.2 on 2024-11-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agent_agreement_client_estate_typeofestate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agent_Id',
            field=models.IntegerField(verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='client_Id',
            field=models.IntegerField(verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='estate_Id',
            field=models.IntegerField(verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='payment_type_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.typeofpayment', verbose_name='Формы оплаты'),
        ),
    ]
