# Generated by Django 5.1.2 on 2024-11-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_agreement_agent_id_alter_agreement_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='payment_type_Id',
            field=models.IntegerField(verbose_name='Формы оплаты'),
        ),
    ]
