# Generated by Django 5.1.2 on 2024-11-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_alter_agreement_payment_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='agent_Id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='client_Id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='estate_Id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='payment_type_Id',
        ),
        migrations.AddField(
            model_name='agent',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agreement', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='client',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agreement', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='typeofestate',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agreement', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='typeofpayment',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agreement', verbose_name='Договор'),
        ),
    ]
