# Generated by Django 5.1.2 on 2024-11-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_remove_agreement_agent_id_remove_agreement_client_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='typeofestate',
            options={'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Типы недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='typeofpayment',
            options={'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
    ]
